### ISSUE TITLE
Peer Review- Adelaida

### ISSUE THREAD

**Issue by adelaidau** [ktacir1/Project-1#2]
Technical Issues:
-Navigation bar should be on all pages of the site including sitemap
-Format the text on the pages so that it is easier to read and understand. (In the about the two paragraphs next to each other)
-Quality of some of the images can be improved.

Suggestions on Content:
-Check for spelling "Schedule is spelled wrong", beautiful is also spelled wrong. This can be very distracting for the reader.
-Make more clear what the page is about. Maybe put a short description on top and then the pictures. This would be useful to understand the purpose of the site.

**Comment by ktacir1** [comment]
Thank you.
