### ISSUE TITLE
Peer Review - Alex Fantappie

### ISSUE THREAD

**Issue by fantappie** [ktacir1/Project-1#3]
Technical bugs/issues:
1.) In the pricing page, providing margin between the table and edged of page could be a good idea
2.) Centering the map integrations on the Famous Locations page could be a good idea 

Content suggestions:
1.) "Beautiful" is misspelled n the home page in the first paragraph
2.) In Famous Locations page, providing a caption under each location w/ a description could be a good idea. 

Cool website overall!

**Comment by ktacir1** [comment]
1.1: Will do thanks!
1.2: Will do it!

2.1:Will fix it!
2.2:Good idea.
